artifact_location: file:///home/runner/work/workflow-CI/workflow-CI/MLProject/mlruns/0
creation_time: 1765890113065
experiment_id: '0'
last_update_time: 1765890113065
lifecycle_stage: active
name: Default
